"""Add product table or modified model

Revision ID: 4a1b443695b3
Revises: 9607db986c45
Create Date: 2025-06-25 17:28:23.741027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a1b443695b3'
down_revision = '9607db986c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', 'UNISEX', name='genderenum'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', 'UNISEX', name='genderenum'),
               nullable=False)

    # ### end Alembic commands ###
