"""Add product table or modified model

Revision ID: e6face02c65d
Revises: 4a1b443695b3
Create Date: 2025-06-25 18:33:40.899855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6face02c65d'
down_revision = '4a1b443695b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('products_subcategorie_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'subcategories', ['subcategory_id'], ['id'])
        batch_op.drop_column('subcategorie_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategorie_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('products_subcategorie_id_fkey'), 'subcategories', ['subcategorie_id'], ['id'])
        batch_op.drop_column('subcategory_id')

    # ### end Alembic commands ###
